### ISSUE TITLE
missing method AppendRecords

### ISSUE THREAD

**Issue by nwhirschfeld** [caddy-dns/lego-deprecated#2] opened 2020-08-22 14:23 UTC
The package implements a Provider, that doesn't implement AppendRecords. This makes caddy crash, when using.

Version of caddy: _v2.2.0-rc.1_
Log of the crash:
```
panic: interface conversion: *legodeprecated.LegoDeprecated is not caddytls.recordManager: missing method AppendRecords
 
 goroutine 1 [running]:
 github.com/caddyserver/caddy/v2/modules/caddytls.(*ACMEIssuer).Provision(0xc00013ac60, 0x27be060, 0xc00078a1c0, 0xc000a000f0, 0xc00095fc70, 0x0, 0x0, 0x0, 0x11, 0x11)
 	github.com/caddyserver/caddy/v2@v2.2.0-rc.1/modules/caddytls/acmeissuer.go:104 +0x654
 github.com/caddyserver/caddy/v2.Context.LoadModuleByID(0x27be060, 0xc00078a1c0, 0xc000a000f0, 0xc00095fc70, 0x0, 0x0, 0x0, 0xc000968220, 0x11, 0xc0000aa480, ...)
 	github.com/caddyserver/caddy/v2@v2.2.0-rc.1/context.go:344 +0x66a
 github.com/caddyserver/caddy/v2.Context.loadModuleInline(0x27be060, 0xc00078a1c0, 0xc000a000f0, 0xc00095fc70, 0x0, 0x0, 0x0, 0x1e3fe11, 0x6, 0x1e3fdf9, ...)
 	github.com/caddyserver/caddy/v2@v2.2.0-rc.1/context.go:394 +0x177
 github.com/caddyserver/caddy/v2.Context.LoadModule(0x27be060, 0xc00078a1c0, 0xc000a000f0, 0xc00095fc70, 0x0, 0x0, 0x0, 0x1e45540, 0xc000257040, 0x22388f4, ...)
 	github.com/caddyserver/caddy/v2@v2.2.0-rc.1/context.go:161 +0x4df
 github.com/caddyserver/caddy/v2/modules/caddytls.(*AutomationPolicy).Provision(0xc000257040, 0xc000932b00, 0x0, 0x0)
 	github.com/caddyserver/caddy/v2@v2.2.0-rc.1/modules/caddytls/automation.go:177 +0x649
 github.com/caddyserver/caddy/v2/modules/caddytls.(*TLS).Provision(0xc000932b00, 0x27be060, 0xc00078a1c0, 0xc000a000f0, 0xc00095fc70, 0x0, 0x0, 0x0, 0x0, 0x0)
 	github.com/caddyserver/caddy/v2@v2.2.0-rc.1/modules/caddytls/tls.go:145 +0x602
 github.com/caddyserver/caddy/v2.Context.LoadModuleByID(0x27be060, 0xc00078a1c0, 0xc000a000f0, 0xc00095fc70, 0x0, 0x0, 0x0, 0xc000a07b24, 0x3, 0xc0005b0480, ...)
 	github.com/caddyserver/caddy/v2@v2.2.0-rc.1/context.go:344 +0x66a
 github.com/caddyserver/caddy/v2.Context.App(0x27be060, 0xc00078a1c0, 0xc000a000f0, 0xc00095fc70, 0x0, 0x0, 0x0, 0xc000a07b24, 0x3, 0xc000a00120, ...)
 	github.com/caddyserver/caddy/v2@v2.2.0-rc.1/context.go:415 +0x165
 github.com/caddyserver/caddy/v2.run.func3(0xc00095fc70, 0x27be060, 0xc00078a1c0, 0xc000a000f0, 0xc00095fc70, 0x0, 0x0, 0x0, 0x0, 0x0)
 	github.com/caddyserver/caddy/v2@v2.2.0-rc.1/caddy.go:388 +0xdc
 github.com/caddyserver/caddy/v2.run(0xc00095fc70, 0x701, 0x0, 0x0)
 	github.com/caddyserver/caddy/v2@v2.2.0-rc.1/caddy.go:393 +0x27a
 github.com/caddyserver/caddy/v2.unsyncedDecodeAndRun(0xc000a2a000, 0x73a, 0x800, 0x7, 0xc000a29710)
 	github.com/caddyserver/caddy/v2@v2.2.0-rc.1/caddy.go:249 +0xf7
 github.com/caddyserver/caddy/v2.changeConfig(0x22236ac, 0x4, 0x222dcd6, 0x7, 0xc0006cd800, 0x73a, 0x800, 0x7fffaa6fde01, 0x0, 0x0)
 	github.com/caddyserver/caddy/v2@v2.2.0-rc.1/caddy.go:156 +0x4bb
 github.com/caddyserver/caddy/v2.Load(...)
 	github.com/caddyserver/caddy/v2@v2.2.0-rc.1/caddy.go:102
 github.com/caddyserver/caddy/v2/cmd.cmdRun(0xc00004ca80, 0x0, 0x0, 0x0)
 	github.com/caddyserver/caddy/v2@v2.2.0-rc.1/cmd/commandfuncs.go:212 +0x397
 github.com/caddyserver/caddy/v2/cmd.Main()
 	github.com/caddyserver/caddy/v2@v2.2.0-rc.1/cmd/main.go:85 +0x239
 main.main()
 	caddy/main.go:10 +0x20
```

config snipet:
```
[...]
      "tls":{
         "automation":{
            "policies":[
               {
                  "subjects":[
                     "my-domain.dns"
                  ],
                  "issuer":{
                     "challenges":{
                        "dns":{
                           "provider":{
                              "name":"lego_deprecated",
                              "provider_name":"inwx"
                           }
                        }
                     },
                     "email":"admin@mydomain.dns",
                     "module":"acme"
                  }
               }
            ]
         }
      }
   }
}
```

**Comment by drbw** [comment] 2020-09-11 16:36
Confirmed, this is currently unusable. It's still important until libdns gets all the old providers which seems to be a long time away.

**Comment by mholt** [comment] 2020-09-11 19:58
@nwhirschfeld @drbw I just tried it, works for me:

```
localhost

tls {
	dns lego_deprecated inwx
}
respond "Yahaha! You found me!"
```

```
$ go run main.go validate --config ~/Dev/_scratch/Caddyfile_caddydns_legodep_2
2020/09/11 19:57:55.696 INFO  using provided configuration  {"config_file": "/Users/matt/Dev/_scratch/Caddyfile_caddydns_legodep_2", "config_adapter": ""}
2020/09/11 19:57:55.697 INFO  tls.cache.maintenance started background certificate maintenance  {"cache": "0xc0003204d0"}
2020/09/11 19:57:55.697 INFO  http  server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS     {"server_name": "srv0", "https_port": 443}
2020/09/11 19:57:55.697 INFO  http  enabling automatic HTTP->HTTPS redirects  {"server_name": "srv0"}
2020/09/11 19:57:55.697 INFO  tls.cache.maintenance stopped background certificate maintenance  {"cache": "0xc0003204d0"}
Valid configuration
```

This calls `Provision()` which is what triggered your panic. I'd be interested to know if you're sure that you're using the latest versions of things.

We can reopen this if it is confirmed to still be a problem.

**Comment by mholt** [comment] 2020-09-11 20:01
Also looks like a duplicate of #1

**Closed as completed** 2020-09-11 20:00 UTC
Labels: duplicate
